# The URL the site will be built for
base_url = "https://cu-rpg-soc.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false


smart_punctuation = true

[extra]
# Put all your custom variables here
president_name = "Oliver Halliwell"
president_crsid = "omh25"

secretary_name = "Joseph Hunt"
secretary_crsid = "jch204"

treasurer_name = "Gethin Brown"
treasurer_crsid = "gsb50"

vice_pres_name = "David Ruston"
vice_pres_crsid = "dr601"

guildmaster_name = "Juthika Sarma"
guildmaster_crsid = "js2858"

technomancer_name = "Benedict Orlich"
technomancer_crsid = "bo310"